### ISSUE TITLE
The `winbar` highlight group is missing?

### ISSUE THREAD

**Issue by ghost** [casr/vim-colors-reference#1]
The `winbar` has been recently [implemented](https://github.com/neovim/neovim/pull/18562) and [released](https://github.com/neovim/neovim/releases/tag/v0.8.0) in Neovim, but the corresponding highlight group is missing in your docs.

**Comment by casr** [comment]
Thanks for your report.

I've synced the Vim and Neovim sources which now includes the `WinBar` and `WinBarNC` highlights.

https://github.com/casr/vim-colors-reference/blob/af51cba002a8022d0fa15bf698a7b597b1f9a255/colors/reference.vim#L266

**Comment by casr** [comment]
In fact, the README needs updating to include how to trigger these groups as well and the others that were added. So I'll reopen until that is done.

**Comment by casr** [comment]
I've added some documentation for `hl-WinBar` and `hl-WinBarNC` in dbf218b794453726c7ca683ca2abd4a44005ddcf. Thanks again for raising this!
